services:
  local-postgres-compose:
    image: postgres
    env_file:
      - ../.env
    ports:
      - "2345:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
